# https://docs.gitlab.com/ee/ci/yaml/README.html

---
image: localhost/deploy-gitlab-tower/tower-cli:latest

before_script:
  - tower-cli version
  
job-template_7:
  script:
    - tower-cli job launch --job-template 7
