# Run this playbook after installing GitLab itself.

---
- name: Deploy GitLab Runner
  hosts: gitlab-runner
  become: true
  roles:
    - role: common
      tags:
        - common
  tasks:
    - block:
        - name: Install Docker
          yum:
            name: docker
            state: present
          tags:
            - docker
        - name: Start Docker daemon
          service:
            name: docker
            enabled: true
            state: started
          tags:
            - docker
        - name: Ensure minimum necessary variables for the role
          assert:
            that:
              # Take from https://<Your_GitLab_Server>/admin/runners
              - gitlab_runner_coordinator_url | d()
              - gitlab_runner_registration_token | d()
        - name: Ensure certs directory exists
          file:
            path: /etc/gitlab-runner/certs
            state: directory
        - name: Bring GitLab's self-signed certificate
          # "synchonize" module or scp command could be used
          run_once: true
          vars:
            gitlab_server: "{{ groups['gitlab'][0] }}"
            temp_crt: "/tmp/gitlab.crt"
          block:
            - name: Fetch GitLab's self-signed certificate
              fetch:
                src: /etc/gitlab/ssl/gitlab.crt
                dest: "{{ temp_crt }}"
                flat: true
              delegate_to: "{{ gitlab_server }}"
            - name: Copy GitLab's self-signed certificate
              copy:
                src: "{{ temp_crt }}"
                dest: /etc/gitlab-runner/certs/{{ gitlab_server }}.crt
        - import_role:
            name: gitlab-runner
          vars:
            # https://github.com/riemers/ansible-gitlab-runner
            gitlab_runner_runners:
              - name: 'Docker GitLab Runner'
                executor: docker
                docker_image: 'centos:8'
      tags:
        - gitlab-runner
