---
- name: Deploy Ansible Tower
  hosts: tower
  become: true
  roles:
    - role: common
      tags:
        - common
    - role: tower
      tags:
        - tower
    - role: podman-unbound
      tags:
        - podman-unbound
