# Doc EN: https://docs.ansible.com/ansible-tower/latest/html/administration/backup_restore.html
# Doc JA: https://docs.ansible.com/ansible-tower/3.5.2/html_ja/administration/backup_restore.html

---
- name: Backup by setup.sh
  command: # noqa 301
    cmd: ./setup.sh -b
    chdir: "{{ tower_home }}"

- name: List the backup files in last modified first way
  shell: "ls -t {{ tower_home }}/tower-backup-????-??-??-*.tar.gz" # noqa 305
  changed_when: false
  register: res_lst

- name: Record the backup file name
  set_fact:
    backup_file: "{{ res_lst.stdout_lines[0] }}"

- name: Bring the backup file if "local_dest" var is defined
  fetch:
    src: "{{ backup_file }}"
    dest: "{{ local_dest }}/{{ inventory_hostname }}_{{ backup_file | basename }}"
    flat: true
  when: local_dest is defined
